### ISSUE TITLE
Can you elaborate on Adaptive Card support?

### ISSUE THREAD

**Issue by v-kydela** [Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#65]
### This issue is for a:
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

The [documentation](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client#features) says the client:

> Displays Adaptive Cards sent from your bot (with some limitations)

When I tried sending an Adaptive Card from my bot to the v1.0.0 client, no card appeared and the input box became unresponsive. I'm assuming I may have sent an unsupported card, but can we get some guidelines to follow if we want our cards to work?

**Comment by chschrae** [comment]
Hi @v-kydela ,
First off, I highly recommend updating to the latest on master for the Direct Line Speech Client. We've made several updates both to the client and to the cognitive services speech SDK. You may have to re-register your bot with the direct line speech channel.

I've done some looking into the code and we are using the 1.2 version of the adaptive cards library, so anything that it supports should also be supported by this. The limitations come from what we are doing with the cards and where we are looking for them.

We are looking for them in the attachments field which is where they will be if following the instructions here: https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/

You should be able to view the json of your activity coming from your bot in the Activity Payload windows. So that may be where your issue is. Also if you have errors in your adaptive card itself, it may not render.

As for what we do with the cards... we only show message boxes for the OnMediaClicked and OnAction events which you can find in the code. The reasoning behind this is we don't know what each scenario would expect to happen depending on the card action/data. This is a big reason for open-sourcing this project so that developers can having a working client that they can alter to test their dialog experience without have to start from scratch.

I hope this all helps. I'll make changes to the readme to add detail about the adaptive cards and how we use them for the next release.

Please feel free to reply if you have any more questions.

**Comment by v-kydela** [comment]
@chschrae - Are you saying Adaptive Card submit actions don't send a message to the bot?

**Comment by chschrae** [comment]
@v-kydela - Not automatically in this case. We are implementing the c# WPF version of the adaptive card library so any "actions" must be handled in the code.

https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/net-wpf/actions

This code exists in the DLS client but only shows a message box. It should be quite easy to change it to call the SendActivityAsync() api on the dialog service connector object. This would allow you to send an activity to your bot.
